#!/bin/bash
# Live Agent Companion — one-line installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/fuyuan-li/gemini_live_agent/main/install.sh | bash
#
# After installation, start the app by typing:
#   holly

set -e

REPO_URL="https://github.com/fuyuan-li/gemini_live_agent.git"
INSTALL_DIR="$HOME/.local/share/companion-agent"
BIN_DIR="$HOME/.local/bin"
CMD="holly"

# ── Colours ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}▶${NC} $*"; }
warn()  { echo -e "${YELLOW}!${NC} $*"; }
error() { echo -e "${RED}✗${NC} $*"; exit 1; }

echo ""
echo "  Live Agent Companion — Installer"
echo "  ─────────────────────────────────"
echo ""

# ── 1. Check Python 3.11+ ────────────────────────────────────────────────────
info "Checking Python version..."
PY=""
for candidate in python3.12 python3.11 python3; do
    if command -v "$candidate" &>/dev/null; then
        PY=$(command -v "$candidate")
        break
    fi
done
[ -z "$PY" ] && error "Python 3.11+ not found. Install from https://python.org or: brew install python@3.11"

PY_VER=$("$PY" -c "import sys; print(sys.version_info.major * 100 + sys.version_info.minor)")
[ "$PY_VER" -lt "311" ] && error "Python 3.11+ required (found $("$PY" --version)). Install from https://python.org or: brew install python@3.11"
info "Using $("$PY" --version)"

# ── 2. Clone or update repo ──────────────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating existing installation at $INSTALL_DIR ..."
    git -C "$INSTALL_DIR" pull --ff-only --quiet
else
    info "Downloading Live Agent Companion..."
    git clone --quiet "$REPO_URL" "$INSTALL_DIR"
fi

# ── 2b. speex system library (required for echo cancellation) ────────────────
if ! command -v brew &>/dev/null; then
    warn "Homebrew not found; skipping speex system library install."
    warn "If echo cancellation fails, install Homebrew then re-run this installer."
else
    for pkg in speexdsp swig; do
        if ! brew list "$pkg" &>/dev/null 2>&1; then
            info "Installing $pkg (required for echo cancellation)..."
            brew install "$pkg" --quiet
        fi
    done
fi

# ── 3. Python environment + dependencies ─────────────────────────────────────
cd "$INSTALL_DIR"
if [ ! -d ".venv" ]; then
    info "Creating Python environment..."
    "$PY" -m venv .venv

    info "Installing Python dependencies (this takes ~1 min the first time)..."
    if command -v brew &>/dev/null && brew list speexdsp &>/dev/null 2>&1; then
        CPATH="$(brew --prefix speexdsp)/include" LIBRARY_PATH="$(brew --prefix speexdsp)/lib" \
            .venv/bin/pip install -q -r requirements.txt
    else
        .venv/bin/pip install -q -r requirements.txt
    fi

    # speexdsp 0.1.1 uses `import imp` which was removed in Python 3.12.
    # Patch the installed glue file to use importlib instead.
    SPEEXDSP_PY=$(find .venv/lib -path "*/speexdsp/speexdsp.py" 2>/dev/null | head -1)
    if [ -n "$SPEEXDSP_PY" ] && grep -qE '^        import imp$' "$SPEEXDSP_PY" 2>/dev/null; then
        info "Patching speexdsp for Python 3.12 compatibility..."
        .venv/bin/python - "$SPEEXDSP_PY" << 'PYEOF'
import sys, re
path = sys.argv[1]
src = open(path).read()
patched = re.sub(
    r'if version_info >= \(2,6,0\):\n    def swig_import_helper\(\):.*?_speexdsp = swig_import_helper\(\)\n    del swig_import_helper',
    '''if version_info >= (2,6,0):
    def swig_import_helper():
        import importlib.util, os
        pkg_dir = os.path.dirname(__file__)
        for fname in os.listdir(pkg_dir):
            if fname.startswith('_speexdsp') and (fname.endswith('.so') or fname.endswith('.pyd')):
                spec = importlib.util.spec_from_file_location('_speexdsp', os.path.join(pkg_dir, fname))
                if spec:
                    mod = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(mod)
                    return mod
        import _speexdsp
        return _speexdsp
    _speexdsp = swig_import_helper()
    del swig_import_helper''',
    src, flags=re.DOTALL)
open(path, 'w').write(patched)
PYEOF
    fi

    info "Downloading Chromium browser (~150 MB)..."
    .venv/bin/python -m playwright install chromium
else
    info "Python environment already set up — skipping dependency install."
    info "  (To force a reinstall, delete $INSTALL_DIR/.venv and run this script again.)"
fi

# ── 4. Install 'companion' command ───────────────────────────────────────────
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/$CMD" << EOF
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand.
exec "$INSTALL_DIR/.venv/bin/python" -m client.companion_app "\$@"
EOF
chmod +x "$BIN_DIR/$CMD"
info "Installed '$CMD' command to $BIN_DIR"

# ── 5. Ensure ~/.local/bin is on PATH ────────────────────────────────────────
add_to_path() {
    local rc="$1"
    if [ -f "$rc" ] && ! grep -q 'companion-agent\|\.local/bin' "$rc" 2>/dev/null; then
        echo '' >> "$rc"
        echo '# Added by companion-agent installer' >> "$rc"
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
        warn "Added ~/.local/bin to PATH in $rc"
        warn "Run:  source $rc  (or open a new terminal)"
    fi
}

if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
    add_to_path "$HOME/.zshrc"
    add_to_path "$HOME/.bashrc"
    export PATH="$HOME/.local/bin:$PATH"  # effective for rest of this script
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}Installation complete!${NC}"
echo ""
echo "  Start the app:"
echo "    companion"
echo ""
echo "  First launch: macOS will ask for Camera and Microphone access — click Allow."
echo ""
