#!/bin/bash
# Wand — one-line installer
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/fuyuan-li/gemini_live_agent/main/install.sh | bash
#
# After installation, start the app by typing:
#   wand

set -e

REPO_URL="https://github.com/fuyuan-li/gemini_live_agent.git"
INSTALL_DIR="$HOME/.local/share/companion-agent"
BIN_DIR="$HOME/.local/bin"
CMD="wand"

# ── Colours ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}▶${NC} $*"; }
warn()  { echo -e "${YELLOW}!${NC} $*"; }
error() { echo -e "${RED}✗${NC} $*"; exit 1; }

echo ""
echo "  Wand — Installer"
echo "  ─────────────────"
echo ""

# ── 1. Check Python 3.11+ ────────────────────────────────────────────────────
info "Checking Python version..."
PY=""
for candidate in python3.12 python3.11 python3; do
    if command -v "$candidate" &>/dev/null; then
        PY=$(command -v "$candidate")
        break
    fi
done
[ -z "$PY" ] && error "Python 3.11+ not found. Install from https://python.org or: brew install python@3.11"

PY_VER=$("$PY" -c "import sys; print(sys.version_info.major * 100 + sys.version_info.minor)")
[ "$PY_VER" -lt "311" ] && error "Python 3.11+ required (found $("$PY" --version)). Install from https://python.org or: brew install python@3.11"
info "Using $("$PY" --version)"

# ── 2. Clone or update repo ──────────────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating existing installation at $INSTALL_DIR ..."
    git -C "$INSTALL_DIR" pull --ff-only --quiet
else
    info "Downloading Wand..."
    git clone --quiet "$REPO_URL" "$INSTALL_DIR"
fi

# ── 3. Python environment + dependencies ─────────────────────────────────────
cd "$INSTALL_DIR"
if [ ! -d ".venv" ]; then
    info "Creating Python environment..."
    "$PY" -m venv .venv

    info "Installing Python dependencies (this takes ~1 min the first time)..."
    .venv/bin/pip install -q -r requirements-client.txt

    info "Downloading Chromium browser (~150 MB)..."
    .venv/bin/python -m playwright install chromium
else
    info "Python environment already set up — skipping dependency install."
    info "  (To force a reinstall, delete $INSTALL_DIR/.venv and run this script again.)"
fi

# ── 4. Install 'companion' command ───────────────────────────────────────────
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/$CMD" << EOF
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand.
cd "$INSTALL_DIR" && exec "$INSTALL_DIR/.venv/bin/python" -m client.companion_app "\$@"
EOF
chmod +x "$BIN_DIR/$CMD"
info "Installed '$CMD' command to $BIN_DIR"

# ── 5. Ensure ~/.local/bin is on PATH ────────────────────────────────────────
add_to_path() {
    local rc="$1"
    if [ -f "$rc" ] && ! grep -q 'companion-agent\|\.local/bin' "$rc" 2>/dev/null; then
        echo '' >> "$rc"
        echo '# Added by companion-agent installer' >> "$rc"
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
        warn "Added ~/.local/bin to PATH in $rc"
        warn "Run:  source $rc  (or open a new terminal)"
    fi
}

if ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
    add_to_path "$HOME/.zshrc"
    add_to_path "$HOME/.bashrc"
    export PATH="$HOME/.local/bin:$PATH"  # effective for rest of this script
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}Installation complete!${NC}"
echo ""
echo "  Start the app:"
echo "    $CMD"
echo ""
echo "  First launch: macOS will ask for Camera and Microphone access — click Allow."
echo ""
