from typing import Any, Protocol

class _Size(Protocol):
    width: float
    height: float

class _Frame(Protocol):
    size: _Size

class NSApplication:
    @classmethod
    def sharedApplication(cls) -> NSApplication: ...
    def nextEventMatchingMask_untilDate_inMode_dequeue_(self, mask: int, date: Any, mode: str, dequeue: bool) -> Any: ...
    def sendEvent_(self, event: Any) -> None: ...
    def updateWindows(self) -> None: ...

class NSColor:
    @classmethod
    def clearColor(cls) -> NSColor: ...
    @classmethod
    def colorWithCalibratedRed_green_blue_alpha_(cls, r: float, g: float, b: float, a: float) -> NSColor: ...
    def set(self) -> None: ...

class NSBezierPath:
    @classmethod
    def bezierPathWithOvalInRect_(cls, rect: Any) -> NSBezierPath: ...
    def fill(self) -> None: ...

class NSView:
    @classmethod
    def alloc(cls) -> Any: ...
    def initWithFrame_(self, frame: Any) -> Any: ...
    def setNeedsDisplay_(self, value: bool) -> None: ...

class NSWindow:
    @classmethod
    def alloc(cls) -> Any: ...
    def initWithContentRect_styleMask_backing_defer_(self, rect: Any, style: int, backing: int, defer: bool) -> NSWindow: ...
    def setReleasedWhenClosed_(self, value: bool) -> None: ...
    def setOpaque_(self, value: bool) -> None: ...
    def setBackgroundColor_(self, color: NSColor) -> None: ...
    def setHasShadow_(self, value: bool) -> None: ...
    def setIgnoresMouseEvents_(self, value: bool) -> None: ...
    def setLevel_(self, level: int) -> None: ...
    def setCollectionBehavior_(self, behavior: int) -> None: ...
    def setContentView_(self, view: NSView) -> None: ...
    def orderFrontRegardless(self) -> None: ...
    def orderOut_(self, sender: Any) -> None: ...
    def close(self) -> None: ...
    def setFrameOrigin_(self, point: tuple[int, int]) -> None: ...

class NSScreen:
    @classmethod
    def mainScreen(cls) -> NSScreen | None: ...
    def frame(self) -> _Frame: ...

def NSMakeRect(x: float, y: float, w: float, h: float) -> Any: ...
def NSRectFill(rect: Any) -> None: ...

NSBackingStoreBuffered: int
NSEventMaskAny: int
NSScreenSaverWindowLevel: int
NSWindowCollectionBehaviorCanJoinAllSpaces: int
NSWindowCollectionBehaviorFullScreenAuxiliary: int
NSWindowStyleMaskBorderless: int
